#!/usr/bin/env python
import sys, os
from intelhex import IntelHex

BYTESPERLINE = 16

if len(sys.argv) < 3:
	print "Usage: ihex2carr.py file.hex file.h [arrayname]"
	print "Uses file.hex as array name if arrayname is not specified"
	sys.exit()

infilename = sys.argv[1]
outfilename = sys.argv[2]
if 3 in sys.argv:
	arrayname = sys.argv[3]
else:
	arrayname = os.path.basename(infilename).replace('.', '_')

ih = IntelHex(infilename)
ihdict = ih.todict()

of = open(outfilename, 'w')
of.write("/* Autogenerated by ihex2carr.py */\n");
of.write("const unsigned char " + arrayname + "[] = {\n")

# Remove upper nibble of addresses
data = dict()
for addr in ihdict:
	data[(addr & 0xFFF)] = ihdict[addr]

maxaddr = ih.maxaddr()
maxaddr &= 0xFFF


try:
	i = 1
	for addr in range(0, maxaddr):
#		print "%x: %x" % (addr, data[addr])
		of.write("%#04x" % (data[addr] if addr in data else 0))
		of.write(", ")
		if i % BYTESPERLINE == 0:
			of.write("\n")
		i+=1
except:
	print "An error occured:", sys.exc_type, ":", sys.exc_value

of.write("}\n");
of.close()
